### ISSUE TITLE
Feed doesn't fully update after revoking authorization and reauthorizing

### ISSUE THREAD

**Issue by waded** [scripting/tweetFeedSupport#4]
I'm seeing an "Invalid or expired token" dialog when manually refreshing feed, and although lastUpdate in ~~both~~ the UI ~~and the RSS~~ show the time I manually refreshed (and/or automated refresh occurred), the RSS doesn't include new tweets, and the lastTweet time is in reference to an older tweet, not the current one.

![image](https://user-images.githubusercontent.com/1535656/185653955-cda0385f-c66d-4693-84ea-72985f13d2b3.png)

This may be a consequence of having revoked authorization at https://twitter.com/settings/connected_apps/819273 at some point. I tried going through authorization a second time, and that doesn't seem to correct it.

I tried using "Sign off Twitter" at Tweetfeed and then "Sign on Twitter", but that didn't seem to be a workaround on its own. (I didn't really expect that to work.) I also tried "Sign off Twitter", then revoking authorization at Twitter, then "Sign on Twitter", which does show the authorization screen again, but that doesn't seem to work around the issue (and I did expect that to work.) The invalid/expired token dialog is still shown, the feed not updated, after having done this. I most recently tried this around 3:20 PM Friday, August 19, 2022 UTC, tried it a couple times yesterday IIRC.

_Originally posted by @waded in https://github.com/scripting/tweetFeedSupport/issues/1#issuecomment-1220780114_

Edit: I struck out something I didn't check before posting. It appears only the UI lastUpdate time changes in this case; the RSS doesn't appear to change at all.

**Comment by scripting** [comment]
where is the dialog appearing?

is your feed still updating? (try tweeting something)

**Comment by waded** [comment]
@scripting Edited description to show the dialog location.

No, the feed is not updating. Last tweet it includes is https://twitter.com/waded/status/1560070117928550401, but I just posted https://twitter.com/waded/status/1560650607098114048 and tried manual update after posting it, saw the dialog, feed still is stuck at https://twitter.com/waded/status/1560070117928550401.

**Comment by scripting** [comment]
I deleted the _waded_ account, so just start over.

**Comment by waded** [comment]
@scripting After you deleted, I signed out at tweetfeed.org then signed on again, reauthorized, and feed updated to include latest tweet. Hitting "Check my tweets..." no longer results in the "Invalid or expired token" dialog, instead getting the "0 new tweets" dialog, which I expect since it's up to date. Thanks.

**Comment by waded** [comment]
To refine cause, I was able to reproduce the "Invalid or expired token" dialog and feed stuck in time issue with a different account - it starts happening immediately after revoking authorization at Twitter. I also was still not able to work around the problem myself - even though tweetfeed goes through the OAuth (re)authorization, perhaps it's not hanging onto the new tokens. For an experiment this is probably fine, and perhaps if you're planning a "delete my data" feature that'd be enough to workaround, useful for other reasons anyway!

**Comment by scripting** [comment]
I know what the fix is. It's too late in the day to attempt it now. ;-)

**Comment by scripting** [comment]
@waded -- I just made the fix. so this should now work.

1. Revoke authorization at Twitter.

2. Log off at tweetfeed.org.

3. Log on again. 

Your feed should once again be updating.

Thanks for your help in finding this mistake in the code. :smile:

**Comment by waded** [comment]
Thanks Dave, it looks fixed. Tested around the scenario a bit and was always able to get the feed updating again after revoking.
